name: build our image for latest

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          qemu-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag mhzawadi/notify_push:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
