name: build our image for dev

on:
  push:
    branches: dev

  repository_dispatch:
    # this event is submited via github.com/bots-house/github-actions-upstream-watch
    types: upstream_commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          qemu-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag mhzawadi/notify_push:dev \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
